/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package prisma.hexagonal.area.y.volumen;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.Desktop;
import java.net.URI;

/**
 *
 * @author Alex
 */
public class Prisma_hexagonal extends javax.swing.JFrame {
ImagenFondo p = new ImagenFondo();
    /**
     * Creates new form Prisma_hexagonal
     */
    public Prisma_hexagonal() {
        initComponents();
        this.add(p,BorderLayout.CENTER);
        this.getContentPane().setBackground(Color.white);
        this.setLocationRelativeTo(null);
    }
    double perimetro, adyacente, apotema, volumen;
    double areaBase, areaLateral, altura, areaTotal,lado;
    private void PrismaHexagonal(){
        try{
            //calculamos la hipotenusa y el lado adyacente 
            //del triángulo para calcular la apotema
            lado = Double.parseDouble(TextField_Lado.getText());
            adyacente = lado / 2;
            perimetro = lado *6;
            Label_Adyacente.setText(adyacente + " cm");
            Label_Hipotenusa.setText(lado + " cm");
            //calculamos el área lateral del prisma hexagonal
            altura = Double.parseDouble(TextField_Altura.getText());
            areaLateral = 6*lado*altura;
            Label_AreaLateral.setText(areaLateral + " cm²");
        }
        catch(Exception e){
            
        }
        //calculamos la apotema del prisma hexagonal
        apotema = Math.sqrt(Math.pow(lado,2)- Math.pow(adyacente,2));
        Label_Pitagora.setText(lado + "²" + " - " + adyacente + "² = " + apotema + " a");
        //calculamos el área base  del prisma hexagonal
        areaBase = perimetro* apotema /2;
        Label_AreaBase.setText(areaBase + " cm²");
        //calculamos el área total del prisma hexagonal
        areaTotal = areaLateral + 2 * areaBase;
        Label_AreaTotal.setText(areaTotal + " cm²");
        //calculamos el volumen del prisma hexagonal
        volumen = areaBase *altura;
        Label_Volumen.setText(volumen + " cm³");
        
        if (TextField_Lado.getText().equals(""))
        {
            Label_Adyacente.setText(0 + " cm");
            Label_Hipotenusa.setText(0 + " cm");
            Label_AreaBase.setText(0 + " cm²");
            Label_AreaTotal.setText(0 + " cm²");
            Label_Pitagora.setText("0² - 0²");
        }
        if (TextField_Altura.getText().equals(""))
        {
            Label_AreaLateral.setText(0 + " cm²");
            Label_Volumen.setText(0 + " cm³");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TextField_Altura = new javax.swing.JTextField();
        TextField_Lado = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Label_AreaLateral = new javax.swing.JLabel();
        Label_AreaBase = new javax.swing.JLabel();
        Label_Volumen = new javax.swing.JLabel();
        Label_AreaTotal = new javax.swing.JLabel();
        Label_Hipotenusa = new javax.swing.JLabel();
        Label_Adyacente = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        Label_Pitagora = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Prisma Hexagonal ");
        setPreferredSize(new java.awt.Dimension(390, 410));
        setResizable(false);

        TextField_Altura.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TextField_AlturaKeyReleased(evt);
            }
        });

        TextField_Lado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TextField_LadoKeyReleased(evt);
            }
        });

        jLabel1.setText("cm");

        jLabel2.setText("cm");

        jLabel3.setText("Area base :");

        jLabel4.setText("Area lateral :");

        jLabel5.setText("Area total :");

        jLabel6.setText("Volumen :");

        Label_AreaLateral.setText("0 cm²");

        Label_AreaBase.setText("0 cm²");

        Label_Volumen.setText("0 cm³");

        Label_AreaTotal.setText("0 cm²");

        Label_Hipotenusa.setText("0 cm");

        Label_Adyacente.setText("0 cm");

        jLabel13.setText("a = √");

        Label_Pitagora.setText("0² - 0²");

        jLabel7.setText("Para mas videos tutoriales");
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        jLabel7.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel7MouseMoved(evt);
            }
        });

        jLabel8.setText("©Programadores HN");

        jLabel9.setText("Teorema de pitágoras");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(TextField_Altura, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel8))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Label_AreaBase)
                            .addComponent(Label_AreaLateral)
                            .addComponent(Label_AreaTotal)
                            .addComponent(Label_Volumen)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(TextField_Lado, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addGap(6, 6, 6)
                                .addComponent(Label_Pitagora)))))
                .addContainerGap(148, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(Label_Hipotenusa)
                        .addGap(95, 95, 95))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(Label_Adyacente)
                        .addGap(106, 106, 106))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(Label_AreaBase))
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(Label_AreaLateral))
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(Label_AreaTotal))
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(Label_Volumen))
                .addGap(38, 38, 38)
                .addComponent(jLabel1)
                .addGap(6, 6, 6)
                .addComponent(TextField_Altura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(jLabel2)
                .addGap(6, 6, 6)
                .addComponent(TextField_Lado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(Label_Hipotenusa)
                .addGap(15, 15, 15)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(Label_Pitagora))
                .addGap(2, 2, 2)
                .addComponent(Label_Adyacente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addGap(6, 6, 6)
                .addComponent(jLabel8)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        try {
            if (Desktop.isDesktopSupported()) {
                Desktop desktop = Desktop.getDesktop();
                if (desktop.isSupported(Desktop.Action.BROWSE)) {
                    desktop.browse(new URI("http://www.youtube.com/alexjpz17"));
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jLabel7MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseMoved
        jLabel7.setCursor(new Cursor(Cursor.HAND_CURSOR));
        jLabel7.setForeground (Color.BLUE);
    }//GEN-LAST:event_jLabel7MouseMoved

    private void TextField_AlturaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextField_AlturaKeyReleased
       PrismaHexagonal();
    }//GEN-LAST:event_TextField_AlturaKeyReleased

    private void TextField_LadoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextField_LadoKeyReleased
        PrismaHexagonal();
    }//GEN-LAST:event_TextField_LadoKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Prisma_hexagonal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Prisma_hexagonal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Prisma_hexagonal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Prisma_hexagonal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Prisma_hexagonal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Label_Adyacente;
    private javax.swing.JLabel Label_AreaBase;
    private javax.swing.JLabel Label_AreaLateral;
    private javax.swing.JLabel Label_AreaTotal;
    private javax.swing.JLabel Label_Hipotenusa;
    private javax.swing.JLabel Label_Pitagora;
    private javax.swing.JLabel Label_Volumen;
    private javax.swing.JTextField TextField_Altura;
    private javax.swing.JTextField TextField_Lado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
